[phases.setup]
nixPkgs = ['bun'] # Bun's the boss

[phases.install]
cmds = ['bun install'] # Install dependencies

[phases.build]
cmds = ['bun run build'] # Build the frontend

[start]
cmd = 'bun run start' # Start the Express server

[staticAssets]
mountPath = '/'
destination = '/app/dist'
