[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install workspace dependencies with minimal flags to avoid issues
cmds = [
  "bun install --frozen-lockfile --ignore-scripts --no-cache --no-verify"
]

[start]
cmd = "cd backend && bun server.js"
