[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install workspace dependencies, skip postinstall scripts to avoid native binary issues
cmds = ["bun install --frozen-lockfile --ignore-scripts"]

[phases.build]
# Build backend only (shared package is TypeScript modules, no build needed)
cmds = [
  "cd backend && bun run build"
]

[start]
cmd = "cd backend && bun server.js"
