[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["curl -fsSL https://bun.sh/install | bash", "export PATH=\"$HOME/.bun/bin:$PATH\"", "bun install"]

[phases.build]
cmds = ["export PATH=\"$HOME/.bun/bin:$PATH\"", "bun run build"]

[start]
cmd = "export PATH=\"$HOME/.bun/bin:$PATH\" && bun run start"
