[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install workspace dependencies first, then backend dependencies
cmds = [
  "cd .. && bun install --frozen-lockfile --production=false",
  "bun install --frozen-lockfile --production=false"
]

[start]
cmd = "bun server.js"
