[phases.setup]
nixPkgs = ["nodejs_20", "bun"]
nixLibs = ["glibc"]

[phases.install]
# Install all dependencies including devDependencies
cmds = ["bun install --frozen-lockfile --production=false"]

[start]
cmd = "cd backend && bun server.js"
