[build]
# Install dependencies from monorepo root
install = """
curl -fsSL https://bun.sh/install | bash
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
bun install
"""

[dev]
# How to start your app
cmd = "cd backend && bun run dev"
