export const CARD_WIDTH_MOBILE = 'w-[375px]'
export const CARD_WIDTH_TABLET = 'md:w-[300px]'
export const CARD_WIDTH_DESKTOP = 'lg:w-[125px]'
export const CARD_HEIGHT_MOBILE = 'h-[500px]'
export const CARD_HEIGHT_TABLET = 'md:h-[300px]'
export const CARD_HEIGHT_DESKTOP = 'lg:h-[300px]'